In [ ]:
pip install pandas

In [15]:
import pandas as pd

# Fazendo a importação do arquivo de cadastro
cadastro = pd.read_csv('cadastro.csv')

# Exibindo a tabela para confirmar a leitura
display(cadastro)

,Nome,Email,Telefone,Endereço
0,Ana Silva,ana.silva@gmail.com,(21) 98765-4321,"Rua das Flores, 123"
1,Pedro Souza,pedro.souza@yahoo.com,(11) 91234-5678,"Avenida Principal, 456"
2,Carla Rocha,carla.rocha@gmail.com,(21) 99876-5432,NaN
3,Mariana Alves,mariana.alves@hotmail.com,(31) 92345-6789,"Travessa da Paz, 789"
4,Lucas Oliveira,lucas.oliveira@gmail.com,(21) 93456-7890,"Rua do Sol, 1011"
5,Fernanda Costa,fernanda.costa@outlook.com,(41) 94567-8901,"Praça da Liberdade, 1213"

Parte 1: Seleções e Filtros

In [4]:
#1. Selecionar apenas a coluna 'Nome':
print(cadastro['Nome'])

0         Ana Silva
1       Pedro Souza
2       Carla Rocha
3     Mariana Alves
4    Lucas Oliveira
5    Fernanda Costa
Name: Nome, dtype: str

In [5]:
#2. Selecionar as colunas 'Nome' e 'Email':
print(cadastro[['Nome', 'Email']])

             Nome                       Email
0       Ana Silva         ana.silva@gmail.com
1     Pedro Souza       pedro.souza@yahoo.com
2     Carla Rocha       carla.rocha@gmail.com
3   Mariana Alves   mariana.alves@hotmail.com
4  Lucas Oliveira    lucas.oliveira@gmail.com
5  Fernanda Costa  fernanda.costa@outlook.com

In [11]:
#3. Selecionar a linha da 'Carla Rocha' (Dica: utilize a indexação implícita .iloc ou filtre pelo nome):
# print(cadastro.iloc[2])
print(cadastro.loc[cadastro['Nome'] == 'Carla Rocha'])

          Nome                  Email         Telefone Endereço
2  Carla Rocha  carla.rocha@gmail.com  (21) 99876-5432      NaN

In [13]:
#4. Selecionar as duas primeiras linhas do DataFrame:
print(cadastro.iloc[0:2])

          Nome                  Email         Telefone                Endereço
0    Ana Silva    ana.silva@gmail.com  (21) 98765-4321     Rua das Flores, 123
1  Pedro Souza  pedro.souza@yahoo.com  (11) 91234-5678  Avenida Principal, 456

In [16]:
#5. Selecionar as linhas onde o telefone começa com o código de área '(21)' 
# (Dica: pesquise sobre o método .str.startswith() ou use .str.contains()):
print(cadastro.loc[cadastro['Telefone'].str.startswith('(21)')])

             Nome                     Email         Telefone  \
0       Ana Silva       ana.silva@gmail.com  (21) 98765-4321
2     Carla Rocha     carla.rocha@gmail.com  (21) 99876-5432
4  Lucas Oliveira  lucas.oliveira@gmail.com  (21) 93456-7890

              Endereço
0  Rua das Flores, 123
2                  NaN
4     Rua do Sol, 1011

In [18]:
#6. Selecionar as linhas onde o email contém '@gmail.com':
print(cadastro.loc[cadastro['Email'].str.endswith('@gmail.com')])

             Nome                     Email         Telefone  \
0       Ana Silva       ana.silva@gmail.com  (21) 98765-4321
2     Carla Rocha     carla.rocha@gmail.com  (21) 99876-5432
4  Lucas Oliveira  lucas.oliveira@gmail.com  (21) 93456-7890

              Endereço
0  Rua das Flores, 123
2                  NaN
4     Rua do Sol, 1011

In [20]:
#7. Selecionar as linhas onde o campo 'Endereço' está vazio (ou seja, quando o Pandas marca como NaN na importação do arquivo.
#  Dica: use o método .isnull()):
print(cadastro.loc[cadastro['Endereço'].isnull()])

          Nome                  Email         Telefone Endereço
2  Carla Rocha  carla.rocha@gmail.com  (21) 99876-5432      NaN

In [25]:
#8. Selecionar o nome e o telefone de quem tem email do 'yahoo.com':
print(cadastro.loc[cadastro['Email'].str.endswith('@yahoo.com'), ['Nome', 'Telefone']])

          Nome         Telefone
1  Pedro Souza  (11) 91234-5678

In [29]:
#9. Selecionar as linhas onde o código de área do telefone é '(11)' OU '(41)':
print(cadastro.loc[(cadastro['Telefone'].str.startswith('(21)')) | (cadastro['Telefone'].str.startswith('(41)'))])

             Nome                       Email         Telefone  \
0       Ana Silva         ana.silva@gmail.com  (21) 98765-4321
2     Carla Rocha       carla.rocha@gmail.com  (21) 99876-5432
4  Lucas Oliveira    lucas.oliveira@gmail.com  (21) 93456-7890
5  Fernanda Costa  fernanda.costa@outlook.com  (41) 94567-8901

                   Endereço
0       Rua das Flores, 123
2                       NaN
4          Rua do Sol, 1011
5  Praça da Liberdade, 1213

In [37]:
#10. Selecionar as linhas onde o endereço NÃO está vazio (Dica: use ~ ou .notnull()):
#print(cadastro.loc[~cadastro['Endereço'].isnull()])
print(cadastro.loc[cadastro['Endereço'].notnull()])

             Nome                       Email         Telefone  \
0       Ana Silva         ana.silva@gmail.com  (21) 98765-4321
1     Pedro Souza       pedro.souza@yahoo.com  (11) 91234-5678
3   Mariana Alves   mariana.alves@hotmail.com  (31) 92345-6789
4  Lucas Oliveira    lucas.oliveira@gmail.com  (21) 93456-7890
5  Fernanda Costa  fernanda.costa@outlook.com  (41) 94567-8901

                   Endereço
0       Rua das Flores, 123
1    Avenida Principal, 456
3      Travessa da Paz, 789
4          Rua do Sol, 1011
5  Praça da Liberdade, 1213

Parte 2: Criar e Alterar Colunas

In [38]:
#1. Adicionar uma coluna 'País' com o valor 'Brasil' para todos os registros.
cadastro['Pais'] = 'Brasil'
print(cadastro)

             Nome                       Email         Telefone  \
0       Ana Silva         ana.silva@gmail.com  (21) 98765-4321
1     Pedro Souza       pedro.souza@yahoo.com  (11) 91234-5678
2     Carla Rocha       carla.rocha@gmail.com  (21) 99876-5432
3   Mariana Alves   mariana.alves@hotmail.com  (31) 92345-6789
4  Lucas Oliveira    lucas.oliveira@gmail.com  (21) 93456-7890
5  Fernanda Costa  fernanda.costa@outlook.com  (41) 94567-8901

                   Endereço    Pais
0       Rua das Flores, 123  Brasil
1    Avenida Principal, 456  Brasil
2                       NaN  Brasil
3      Travessa da Paz, 789  Brasil
4          Rua do Sol, 1011  Brasil
5  Praça da Liberdade, 1213  Brasil

In [ ]:
#2. Adicionar uma coluna 'Tem_Gmail' que seja True se o email da pessoa contiver '@gmail.com' e False caso contrário.
cadastro['Tem_Gmail'] = cadastro['Email'].str.contains('@gmail.com')
print(cadastro)

In [ ]:
#3. Criar uma nova coluna chamada 'DDD' contendo apenas o código de área do telefone (removendo os parênteses e o restante do número).
cadastro['DDD'] = cadastro['Telefone'].str.slice(0, 3)
print(cadastro)

             Nome                       Email         Telefone  \
0       Ana Silva         ana.silva@gmail.com  (21) 98765-4321
1     Pedro Souza       pedro.souza@yahoo.com  (11) 91234-5678
2     Carla Rocha       carla.rocha@gmail.com  (21) 99876-5432
3   Mariana Alves   mariana.alves@hotmail.com  (31) 92345-6789
4  Lucas Oliveira    lucas.oliveira@gmail.com  (21) 93456-7890
5  Fernanda Costa  fernanda.costa@outlook.com  (41) 94567-8901

                   Endereço    Pais  Tem_Gmail DDD
0       Rua das Flores, 123  Brasil       True  21
1    Avenida Principal, 456  Brasil      False  11
2                       NaN  Brasil       True  21
3      Travessa da Paz, 789  Brasil      False  31
4          Rua do Sol, 1011  Brasil       True  21
5  Praça da Liberdade, 1213  Brasil      False  41

In [72]:
cadastro['Telefone'].str[1:3]

0    87
1    12
2    98
3    23
4    34
5    45
Name: Telefone, dtype: str

In [56]:
#4. Remover o valor do DDD (incluindo os parênteses e o espaço) e deixar apenas o número na coluna 'Telefone'.
cadastro['Telefone'] = cadastro['Telefone'].str.slice(5, 16)
print(cadastro)

             Nome                       Email    Telefone  \
0       Ana Silva         ana.silva@gmail.com  98765-4321
1     Pedro Souza       pedro.souza@yahoo.com  91234-5678
2     Carla Rocha       carla.rocha@gmail.com  99876-5432
3   Mariana Alves   mariana.alves@hotmail.com  92345-6789
4  Lucas Oliveira    lucas.oliveira@gmail.com  93456-7890
5  Fernanda Costa  fernanda.costa@outlook.com  94567-8901

                   Endereço    Pais  Tem_Gmail DDD
0       Rua das Flores, 123  Brasil       True  21
1    Avenida Principal, 456  Brasil      False  11
2                       NaN  Brasil       True  21
3      Travessa da Paz, 789  Brasil      False  31
4          Rua do Sol, 1011  Brasil       True  21
5  Praça da Liberdade, 1213  Brasil      False  41

In [57]:
#5. Modificar a coluna 'Nome' para que todos os nomes fiquem em letras maiúsculas.
cadastro['Nome'] = cadastro['Nome'].str.upper()
print(cadastro)

             Nome                       Email    Telefone  \
0       ANA SILVA         ana.silva@gmail.com  98765-4321
1     PEDRO SOUZA       pedro.souza@yahoo.com  91234-5678
2     CARLA ROCHA       carla.rocha@gmail.com  99876-5432
3   MARIANA ALVES   mariana.alves@hotmail.com  92345-6789
4  LUCAS OLIVEIRA    lucas.oliveira@gmail.com  93456-7890
5  FERNANDA COSTA  fernanda.costa@outlook.com  94567-8901

                   Endereço    Pais  Tem_Gmail DDD
0       Rua das Flores, 123  Brasil       True  21
1    Avenida Principal, 456  Brasil      False  11
2                       NaN  Brasil       True  21
3      Travessa da Paz, 789  Brasil      False  31
4          Rua do Sol, 1011  Brasil       True  21
5  Praça da Liberdade, 1213  Brasil      False  41

In [67]:
#6. Adicionar uma coluna 'Email_Provedor' que contenha apenas o provedor de email (por exemplo, 'gmail.com', 'yahoo.com', 'hotmail.com').
#cadastro['Email_Provedor'] = cadastro['Email'].str.split('@').str[1]
display(cadastro)

,Nome,Email,Telefone,Endereço,Pais,Tem_Gmail,DDD,Email_Provedor
0,ANA SILVA,ana.silva@gmail.com,98765-4321,"Rua das Flores, 123",Brasil,True,21,gmail.com
1,PEDRO SOUZA,pedro.souza@yahoo.com,91234-5678,"Avenida Principal, 456",Brasil,False,11,yahoo.com
2,CARLA ROCHA,carla.rocha@gmail.com,99876-5432,NaN,Brasil,True,21,gmail.com
3,MARIANA ALVES,mariana.alves@hotmail.com,92345-6789,"Travessa da Paz, 789",Brasil,False,31,hotmail.com
4,LUCAS OLIVEIRA,lucas.oliveira@gmail.com,93456-7890,"Rua do Sol, 1011",Brasil,True,21,gmail.com
5,FERNANDA COSTA,fernanda.costa@outlook.com,94567-8901,"Praça da Liberdade, 1213",Brasil,False,41,outlook.com

In [68]:
#7. Para os Endereços não preenchidos (que ficaram como NaN), preencher com o texto 'NÃO INFORMADO'.
cadastro['Endereço'] = cadastro['Endereço'].fillna('NÃO INFORMADO')
display(cadastro)

,Nome,Email,Telefone,Endereço,Pais,Tem_Gmail,DDD,Email_Provedor
0,ANA SILVA,ana.silva@gmail.com,98765-4321,"Rua das Flores, 123",Brasil,True,21,gmail.com
1,PEDRO SOUZA,pedro.souza@yahoo.com,91234-5678,"Avenida Principal, 456",Brasil,False,11,yahoo.com
2,CARLA ROCHA,carla.rocha@gmail.com,99876-5432,NÃO INFORMADO,Brasil,True,21,gmail.com
3,MARIANA ALVES,mariana.alves@hotmail.com,92345-6789,"Travessa da Paz, 789",Brasil,False,31,hotmail.com
4,LUCAS OLIVEIRA,lucas.oliveira@gmail.com,93456-7890,"Rua do Sol, 1011",Brasil,True,21,gmail.com
5,FERNANDA COSTA,fernanda.costa@outlook.com,94567-8901,"Praça da Liberdade, 1213",Brasil,False,41,outlook.com