In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\epuel\appdata\local\programs\python\python313\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\epuel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\epuel\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\epuel\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\epuel\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv('carros.csv', index_col=0)
display(df)

        Marca   Modelo   Ano  Quilometragem  Preço Diária  Disponível
A  Volkswagen      Gol  2021          70263            70       False
B   Chevrolet    Cruze  2018          26023           107        True
C     Hyundai     HB20  2022          51090            71       False
D  Volkswagen      Gol  2019          77221           138        True
E      Toyota  Corolla  2021          74820            98        True
F      Toyota  Corolla  2017          10769           108        True
G      Toyota    Etios  2021          69735            64       False
H     Hyundai     HB20  2022          72955           100        True
I      Toyota  Corolla  2019          74925           157        True
J  Volkswagen      Gol  2018          77969           104        True

In [7]:
primeiro_carro = df.iloc[0]
display(primeiro_carro)

Marca            Volkswagen
Modelo                  Gol
Ano                    2021
Quilometragem         70263
Preço Diária             70
Disponível            False
Name: A, dtype: object

In [8]:
primeiros_cinco = df.iloc[0:5]
display(primeiros_cinco)

        Marca   Modelo   Ano  Quilometragem  Preço Diária  Disponível
A  Volkswagen      Gol  2021          70263            70       False
B   Chevrolet    Cruze  2018          26023           107        True
C     Hyundai     HB20  2022          51090            71       False
D  Volkswagen      Gol  2019          77221           138        True
E      Toyota  Corolla  2021          74820            98        True

In [10]:
carro_b = df.loc["B"]
display(carro_b)

Marca            Chevrolet
Modelo               Cruze
Ano                   2018
Quilometragem        26023
Preço Diária           107
Disponível            True
Name: B, dtype: object

In [11]:
marcas_e_modelos = df.loc['A':'C', ['Marca', 'Modelo']]
display(marcas_e_modelos)

        Marca Modelo
A  Volkswagen    Gol
B   Chevrolet  Cruze
C     Hyundai   HB20

In [12]:
opcoes_cliente = df[(df['Marca'] == 'Toyota') | (df['Preço Diária'] < 80)]
display(opcoes_cliente)

        Marca   Modelo   Ano  Quilometragem  Preço Diária  Disponível
A  Volkswagen      Gol  2021          70263            70       False
C     Hyundai     HB20  2022          51090            71       False
E      Toyota  Corolla  2021          74820            98        True
F      Toyota  Corolla  2017          10769           108        True
G      Toyota    Etios  2021          69735            64       False
I      Toyota  Corolla  2019          74925           157        True

In [13]:
populares = df[df['Modelo'].isin(['Gol', 'HB20'])]
display(populares)

        Marca Modelo   Ano  Quilometragem  Preço Diária  Disponível
A  Volkswagen    Gol  2021          70263            70       False
C     Hyundai   HB20  2022          51090            71       False
D  Volkswagen    Gol  2019          77221           138        True
H     Hyundai   HB20  2022          72955           100        True
J  Volkswagen    Gol  2018          77969           104        True

In [14]:
semanal = df['Preço Diária'] * 7
display(semanal)

A     490
B     749
C     497
D     966
E     686
F     756
G     448
H     700
I    1099
J     728
Name: Preço Diária, dtype: int64